# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        connection-timeout: 5000ms
        threads:
            max: 1000
            min-spare: 30
    port: 8099
    servlet:
        context-path: /api/v1
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/optisun?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Colombo
            username: optisun
            password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 100000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

    redis:
        open: true
        database: 1
        host: localhost
        port: 6379
        password:
        timeout: 6000ms
        jedis:
            pool:
                max-active: 1000
                max-wait: -1ms
                max-idle: 10
                min-idle: 5
    cache:
        type: redis
    mvc:
        throw-exception-if-no-handler-found: true
    #    add-mappings: false

    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: CTJG_86866666
        virtual-host: /